// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: generic_reply.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_generic_5freply_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_generic_5freply_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3020000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3020003 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
#include <google/protobuf/any.pb.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_generic_5freply_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_generic_5freply_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_generic_5freply_2eproto;
namespace tcp_kit {
class GenericReply;
struct GenericReplyDefaultTypeInternal;
extern GenericReplyDefaultTypeInternal _GenericReply_default_instance_;
}  // namespace tcp_kit
PROTOBUF_NAMESPACE_OPEN
template<> ::tcp_kit::GenericReply* Arena::CreateMaybeMessage<::tcp_kit::GenericReply>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace tcp_kit {

enum GenericReply_Code : int {
  GenericReply_Code_UNKNOWN_ERR = 0,
  GenericReply_Code_SUCCESS = 200,
  GenericReply_Code_RES_NOT_FOUND = 404,
  GenericReply_Code_INTERNAL_SERVER_ERR = 500,
  GenericReply_Code_GenericReply_Code_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  GenericReply_Code_GenericReply_Code_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool GenericReply_Code_IsValid(int value);
constexpr GenericReply_Code GenericReply_Code_Code_MIN = GenericReply_Code_UNKNOWN_ERR;
constexpr GenericReply_Code GenericReply_Code_Code_MAX = GenericReply_Code_INTERNAL_SERVER_ERR;
constexpr int GenericReply_Code_Code_ARRAYSIZE = GenericReply_Code_Code_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* GenericReply_Code_descriptor();
template<typename T>
inline const std::string& GenericReply_Code_Name(T enum_t_value) {
  static_assert(::std::is_same<T, GenericReply_Code>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function GenericReply_Code_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    GenericReply_Code_descriptor(), enum_t_value);
}
inline bool GenericReply_Code_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, GenericReply_Code* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<GenericReply_Code>(
    GenericReply_Code_descriptor(), name, value);
}
// ===================================================================

class GenericReply final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:tcp_kit.GenericReply) */ {
 public:
  inline GenericReply() : GenericReply(nullptr) {}
  ~GenericReply() override;
  explicit PROTOBUF_CONSTEXPR GenericReply(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  GenericReply(const GenericReply& from);
  GenericReply(GenericReply&& from) noexcept
    : GenericReply() {
    *this = ::std::move(from);
  }

  inline GenericReply& operator=(const GenericReply& from) {
    CopyFrom(from);
    return *this;
  }
  inline GenericReply& operator=(GenericReply&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const GenericReply& default_instance() {
    return *internal_default_instance();
  }
  static inline const GenericReply* internal_default_instance() {
    return reinterpret_cast<const GenericReply*>(
               &_GenericReply_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(GenericReply& a, GenericReply& b) {
    a.Swap(&b);
  }
  inline void Swap(GenericReply* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(GenericReply* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  GenericReply* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<GenericReply>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const GenericReply& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const GenericReply& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to, const ::PROTOBUF_NAMESPACE_ID::Message& from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(GenericReply* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "tcp_kit.GenericReply";
  }
  protected:
  explicit GenericReply(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  typedef GenericReply_Code Code;
  static constexpr Code UNKNOWN_ERR =
    GenericReply_Code_UNKNOWN_ERR;
  static constexpr Code SUCCESS =
    GenericReply_Code_SUCCESS;
  static constexpr Code RES_NOT_FOUND =
    GenericReply_Code_RES_NOT_FOUND;
  static constexpr Code INTERNAL_SERVER_ERR =
    GenericReply_Code_INTERNAL_SERVER_ERR;
  static inline bool Code_IsValid(int value) {
    return GenericReply_Code_IsValid(value);
  }
  static constexpr Code Code_MIN =
    GenericReply_Code_Code_MIN;
  static constexpr Code Code_MAX =
    GenericReply_Code_Code_MAX;
  static constexpr int Code_ARRAYSIZE =
    GenericReply_Code_Code_ARRAYSIZE;
  static inline const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor*
  Code_descriptor() {
    return GenericReply_Code_descriptor();
  }
  template<typename T>
  static inline const std::string& Code_Name(T enum_t_value) {
    static_assert(::std::is_same<T, Code>::value ||
      ::std::is_integral<T>::value,
      "Incorrect type passed to function Code_Name.");
    return GenericReply_Code_Name(enum_t_value);
  }
  static inline bool Code_Parse(::PROTOBUF_NAMESPACE_ID::ConstStringParam name,
      Code* value) {
    return GenericReply_Code_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  enum : int {
    kMsgFieldNumber = 2,
    kBodyFieldNumber = 3,
    kCodeFieldNumber = 1,
  };
  // optional string msg = 2;
  bool has_msg() const;
  private:
  bool _internal_has_msg() const;
  public:
  void clear_msg();
  const std::string& msg() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_msg(ArgT0&& arg0, ArgT... args);
  std::string* mutable_msg();
  PROTOBUF_NODISCARD std::string* release_msg();
  void set_allocated_msg(std::string* msg);
  private:
  const std::string& _internal_msg() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_msg(const std::string& value);
  std::string* _internal_mutable_msg();
  public:

  // optional .google.protobuf.Any body = 3;
  bool has_body() const;
  private:
  bool _internal_has_body() const;
  public:
  void clear_body();
  const ::PROTOBUF_NAMESPACE_ID::Any& body() const;
  PROTOBUF_NODISCARD ::PROTOBUF_NAMESPACE_ID::Any* release_body();
  ::PROTOBUF_NAMESPACE_ID::Any* mutable_body();
  void set_allocated_body(::PROTOBUF_NAMESPACE_ID::Any* body);
  private:
  const ::PROTOBUF_NAMESPACE_ID::Any& _internal_body() const;
  ::PROTOBUF_NAMESPACE_ID::Any* _internal_mutable_body();
  public:
  void unsafe_arena_set_allocated_body(
      ::PROTOBUF_NAMESPACE_ID::Any* body);
  ::PROTOBUF_NAMESPACE_ID::Any* unsafe_arena_release_body();

  // .tcp_kit.GenericReply.Code code = 1;
  void clear_code();
  ::tcp_kit::GenericReply_Code code() const;
  void set_code(::tcp_kit::GenericReply_Code value);
  private:
  ::tcp_kit::GenericReply_Code _internal_code() const;
  void _internal_set_code(::tcp_kit::GenericReply_Code value);
  public:

  // @@protoc_insertion_point(class_scope:tcp_kit.GenericReply)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr msg_;
  ::PROTOBUF_NAMESPACE_ID::Any* body_;
  int code_;
  friend struct ::TableStruct_generic_5freply_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// GenericReply

// .tcp_kit.GenericReply.Code code = 1;
inline void GenericReply::clear_code() {
  code_ = 0;
}
inline ::tcp_kit::GenericReply_Code GenericReply::_internal_code() const {
  return static_cast< ::tcp_kit::GenericReply_Code >(code_);
}
inline ::tcp_kit::GenericReply_Code GenericReply::code() const {
  // @@protoc_insertion_point(field_get:tcp_kit.GenericReply.code)
  return _internal_code();
}
inline void GenericReply::_internal_set_code(::tcp_kit::GenericReply_Code value) {
  
  code_ = value;
}
inline void GenericReply::set_code(::tcp_kit::GenericReply_Code value) {
  _internal_set_code(value);
  // @@protoc_insertion_point(field_set:tcp_kit.GenericReply.code)
}

// optional string msg = 2;
inline bool GenericReply::_internal_has_msg() const {
  bool value = (_has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool GenericReply::has_msg() const {
  return _internal_has_msg();
}
inline void GenericReply::clear_msg() {
  msg_.ClearToEmpty();
  _has_bits_[0] &= ~0x00000001u;
}
inline const std::string& GenericReply::msg() const {
  // @@protoc_insertion_point(field_get:tcp_kit.GenericReply.msg)
  return _internal_msg();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void GenericReply::set_msg(ArgT0&& arg0, ArgT... args) {
 _has_bits_[0] |= 0x00000001u;
 msg_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:tcp_kit.GenericReply.msg)
}
inline std::string* GenericReply::mutable_msg() {
  std::string* _s = _internal_mutable_msg();
  // @@protoc_insertion_point(field_mutable:tcp_kit.GenericReply.msg)
  return _s;
}
inline const std::string& GenericReply::_internal_msg() const {
  return msg_.Get();
}
inline void GenericReply::_internal_set_msg(const std::string& value) {
  _has_bits_[0] |= 0x00000001u;
  msg_.Set(value, GetArenaForAllocation());
}
inline std::string* GenericReply::_internal_mutable_msg() {
  _has_bits_[0] |= 0x00000001u;
  return msg_.Mutable(GetArenaForAllocation());
}
inline std::string* GenericReply::release_msg() {
  // @@protoc_insertion_point(field_release:tcp_kit.GenericReply.msg)
  if (!_internal_has_msg()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000001u;
  auto* p = msg_.Release();
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (msg_.IsDefault()) {
    msg_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  return p;
}
inline void GenericReply::set_allocated_msg(std::string* msg) {
  if (msg != nullptr) {
    _has_bits_[0] |= 0x00000001u;
  } else {
    _has_bits_[0] &= ~0x00000001u;
  }
  msg_.SetAllocated(msg, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (msg_.IsDefault()) {
    msg_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:tcp_kit.GenericReply.msg)
}

// optional .google.protobuf.Any body = 3;
inline bool GenericReply::_internal_has_body() const {
  bool value = (_has_bits_[0] & 0x00000002u) != 0;
  PROTOBUF_ASSUME(!value || body_ != nullptr);
  return value;
}
inline bool GenericReply::has_body() const {
  return _internal_has_body();
}
inline const ::PROTOBUF_NAMESPACE_ID::Any& GenericReply::_internal_body() const {
  const ::PROTOBUF_NAMESPACE_ID::Any* p = body_;
  return p != nullptr ? *p : reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Any&>(
      ::PROTOBUF_NAMESPACE_ID::_Any_default_instance_);
}
inline const ::PROTOBUF_NAMESPACE_ID::Any& GenericReply::body() const {
  // @@protoc_insertion_point(field_get:tcp_kit.GenericReply.body)
  return _internal_body();
}
inline void GenericReply::unsafe_arena_set_allocated_body(
    ::PROTOBUF_NAMESPACE_ID::Any* body) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(body_);
  }
  body_ = body;
  if (body) {
    _has_bits_[0] |= 0x00000002u;
  } else {
    _has_bits_[0] &= ~0x00000002u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:tcp_kit.GenericReply.body)
}
inline ::PROTOBUF_NAMESPACE_ID::Any* GenericReply::release_body() {
  _has_bits_[0] &= ~0x00000002u;
  ::PROTOBUF_NAMESPACE_ID::Any* temp = body_;
  body_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::PROTOBUF_NAMESPACE_ID::Any* GenericReply::unsafe_arena_release_body() {
  // @@protoc_insertion_point(field_release:tcp_kit.GenericReply.body)
  _has_bits_[0] &= ~0x00000002u;
  ::PROTOBUF_NAMESPACE_ID::Any* temp = body_;
  body_ = nullptr;
  return temp;
}
inline ::PROTOBUF_NAMESPACE_ID::Any* GenericReply::_internal_mutable_body() {
  _has_bits_[0] |= 0x00000002u;
  if (body_ == nullptr) {
    auto* p = CreateMaybeMessage<::PROTOBUF_NAMESPACE_ID::Any>(GetArenaForAllocation());
    body_ = p;
  }
  return body_;
}
inline ::PROTOBUF_NAMESPACE_ID::Any* GenericReply::mutable_body() {
  ::PROTOBUF_NAMESPACE_ID::Any* _msg = _internal_mutable_body();
  // @@protoc_insertion_point(field_mutable:tcp_kit.GenericReply.body)
  return _msg;
}
inline void GenericReply::set_allocated_body(::PROTOBUF_NAMESPACE_ID::Any* body) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(body_);
  }
  if (body) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(body));
    if (message_arena != submessage_arena) {
      body = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, body, submessage_arena);
    }
    _has_bits_[0] |= 0x00000002u;
  } else {
    _has_bits_[0] &= ~0x00000002u;
  }
  body_ = body;
  // @@protoc_insertion_point(field_set_allocated:tcp_kit.GenericReply.body)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace tcp_kit

PROTOBUF_NAMESPACE_OPEN

template <> struct is_proto_enum< ::tcp_kit::GenericReply_Code> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::tcp_kit::GenericReply_Code>() {
  return ::tcp_kit::GenericReply_Code_descriptor();
}

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_generic_5freply_2eproto
